# https://docs.github.com/en/actions/guides/publishing-docker-images
name: Build and publish Docker image

on:
  push:
  pull_request:

jobs:
  build_and_push:
    name: Build docker image, push to GitHub registry
    runs-on: ubuntu-latest
    steps:

      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/manics/connecttunnel-docker

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
